### PR TITLE
[OB-3664] Fixed CustomComponentTest from hanging

### PR DESCRIPTION
**Pull request by MAG-mv**
- Added a test timeout to the loop to prevent hanging in the future

### CODE REVIEW

**Review by MAG-SamBirley — APPROVED** [review]
We're introducing a workaround for a test failure with this change, but that said it's a test for a feature with low-utilisation, and it's actively blocking high-prio work. 

I'd like to find and fix the true issue, but I'm ok doing that in a future PR.

**Comment by MAG-mv** [comment]
@MAG-SamBirley The true issue was because of an error on my development branch, which I am fixing in my PR

**Comment by MAG-SamBirley** [comment]
> @MAG-SamBirley The true issue was because of an error on my development branch, which I am fixing in my PR

Given that if we had this PR merged, we would not have caught the true issue, as we sure we want to merge this change?

**Comment by MAG-mv** [comment]
> Given that if we had this PR merged, we would not have caught the true issue, are we sure we want to merge this change?

This PR contains a check to ensure the callback is called: EXPECT_TRUE(GotAllEntities);

This will make the issue more clear instead of hangning

**Comment by MAG-SamBirley** [comment]
> > Given that if we had this PR merged, we would not have caught the true issue, are we sure we want to merge this change?
> 
> This PR contains a check to ensure the callback is called: EXPECT_TRUE(GotAllEntities);
> 
> This will make the issue more clear instead of hanging

Ah, yes, sorry for missing that. That's perfect!

**Pull request merged**
