### PR TITLE
[OF-1061] refac: Create helper functions and internal tests

### PR DESCRIPTION
**Pull request by Mag-JB**
connected-spaces-platform Pull Request

**For the reviewer**

* [x] If required, are the changes covered by appropriate tests?
* [x] Are any public-facing API changes well documented?
* [x] Is the code easily readable and extensible and/or follow existing conventions?

### CODE REVIEW

**Review by MAG-SamBirley — CHANGES_REQUESTED** [review]
Can we also test unhappy paths, for example including (but not limited to) using  IdCheckValidTest to test what happens if you specify an ID that isn't in the array.

**Comment by MAG-SamBirley** [comment]
Definitely on the right track!

**Comment by Mag-JB** [comment]
already done in `CSP_INTERNAL_TEST(CSPEngine, SpaceHelperTests, IdCheckInValidTest)`

**Comment by Mag-JB** [comment]
second look, looks good to me!

**Review by MAG-SamBirley — APPROVED** [review]

**Pull request merged**
