### PR TITLE
#524 Check for null when calling functions that return a pointer

### PR DESCRIPTION
**Pull request by magnopus-swifty**
Modify the templates so functions that return values store the result in a temporary local var. This is then checked for `null` so a C# `null` can be returned instead of a wrapped `null` (which would cause a hard crash if dereferenced).

### CODE REVIEW

**Comment by magnopus-swifty** [comment]
This PR changes the output for functions that returns pointers (like `GetParentEntity()`) from:

```csharp
        public Csp.Multiplayer.SpaceEntity GetParentEntity()
        {
            var _result = new Csp.Multiplayer.SpaceEntity(
                csp_multiplayer_SpaceEntity_GetParentEntityC_SpaceEntityP(_ptr)
            );

            return _result;
        }
```

to

```csharp
        public Csp.Multiplayer.SpaceEntity GetParentEntity()
        {
            var _value = csp_multiplayer_SpaceEntity_GetParentEntityC_SpaceEntityP(_ptr);

            if (_value.Equals(NativePointer.Zero))
                return null;

            var _result = new Csp.Multiplayer.SpaceEntity(_value);

            return _result;
        }
```

**Comment by MAG-SamBirley** [comment]
Firstly, this change is awesome. Secondly, it looks like this change may have brought some of your other recent changes along for the ride (it has changes to the commit message template and chevron module removal). Can we get rid of those for this PR?

**Comment by magnopus-swifty** [comment]
> Firstly, this change is awesome. Secondly, it looks like this change may have brought some of your other recent changes along for the ride (it has changes to the commit message template and chevron module removal). Can we get rid of those for this PR?

Those will get diffed out once those changes are merged in. Unfortunately there isn't a nice way to build on top of other in-progress work with Github.

**Comment by mag-richardzirbes** [comment]
Do we need to put any methods that could return a null value inside a try-catch block now, with the usage of the helper CheckNativePointer(pointer)? (I only sort-of understand the mustache syntax)

**Comment by magnopus-swifty** [comment]
> Do we need to put any methods that could return a null value inside a try-catch block now, with the usage of the helper CheckNativePointer(pointer)? (I only sort-of understand the mustache syntax)

No - if `null` is a valid return (e.g. in the case of `GetParentEntity()`) then the C# wrapper will also just return null (rather than an invalid object wrapping a null).

If a method has a return type that's a reference, e.g. `const SpaceTransform& GetTransform() const` then the `CheckNativePointer` will _ensure_ that a non-null pointer is returned (it shouldn't ever do so) and will _always_ return a valid object.

**Comment by magnopus-swifty** [comment]
Methods returning a reference will check the reference for non-nullness (only in Debug builds):

e.g. `SpaceEntity.GetTransform()` calling `const SpaceTransform& GetTransform() const`:

```csharp
        public Csp.Multiplayer.SpaceTransform GetTransform()
        {
            var _value = csp_multiplayer_SpaceEntity_GetTransformC_SpaceTransformRC(_ptr);

            WrapperHelper.CheckNativePointer(_value);

            var _result = new Csp.Multiplayer.SpaceTransform(_value);

            return _result;
        }
```

Methods where null is a valid return will also return `null` on the C# side, e.g. `GetParentEntity()`.

**Review by MAG-SamBirley — APPROVED** [review]
Change looks good!

**Review by MAG-mv — APPROVED** [review]

**Review by MAG-mv — APPROVED** [review]

**Pull request merged**
