### PR TITLE
Asset: make ThirdParty properties public, remove methods

### PR DESCRIPTION
**Pull request by mag-richardzirbes**
To make the Asset class a full DTO, change the methods to properties. This will help simplify the C# Foundation layer & memory management wrapping.

### CODE REVIEW

**Comment by mag-richardzirbes** [comment]
@MAG-AlessioRegalbuto @mag-michelleshyr FYI

**Review by MAG-AdamThorn — APPROVED** [review]

**Review by MAG-ElliotMorris — APPROVED** [review]

**Review by MAG-AdamThorn — APPROVED** [review]

**Comment by mag-richardzirbes** [comment]
I'm not sure the originating cause of (what I think is) the tests build error:
```
 C:\teamcity\uk-hw-win-01-01\work\d578f8b65d37e27d\ThirdParty\googletest\include\gtest\gtest.h(1746,6): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const T1' (or there is no acceptable conversion) [C:\teamcity\uk-hw-win-01-01\work\d578f8b65d37e27d\MultiplayerTestRunner\MultiplayerTestRunner.vcxproj]
15:37:38             with
15:37:38             [
15:37:38                 T1=std::pair<std::string,std::string>
15:37:38             ]
```

**Comment by MAG-ElliotMorris** [comment]
Aye, this isn't you, it's a side effect of another change and a mismatched CI config, we're working on getting it resolved.

**Comment by MAG-ElliotMorris** [comment]
@mag-richardzirbes I took the liberty of rerunning your test jobs after we'd commited a fix, sorry for the bother.

**Review by MAG-ElliotMorris — APPROVED** [review]

**Pull request merged**
